name: kungfu
version: 1.0.1
api-version: 1.20
author: quiquelhappy
main: co.purevanilla.mcplugins.kungfu.Main
softdepend:
  - VentureChat
commands:
  flushchat:
    permission: "kungfu.flush"
    usage: "/flushchat [max-lines]"